import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Text, Heading } from "@chakra-ui/react"


import CustomNavBar from '../components/navbarcontainer'
import CustomBtn from '../components/button'
import ImageCap from '../components/captionimage'
import ContentStack from '../components/contentstack'
import Section from '../components/section'
import { useRef } from 'react'

import { HStack } from '@chakra-ui/react'

export default function Home() {

  const about = useRef<HTMLDivElement>(null)
  const home = useRef<HTMLDivElement>(null)
  const freq = useRef<HTMLDivElement>(null)

  return (   
    <div> 

      <CustomNavBar 
        onAboutClick={() => about.current?.scrollIntoView({ behavior: 'smooth'})}
        onHomeClick={() => home.current?.scrollIntoView({ behavior: 'smooth' })}
        onFreqClick={() => freq.current?.scrollIntoView({ behavior: 'smooth' })}
      />

      <div className={styles.backgroundImage}>
        <div className={styles.logo}>
        </div>

        <p className={styles.description}>
          Design smarter. Not harder.
          <br></br>
          <div style={{padding: "2em 0"}}>
            <CustomBtn placeholder="Sign Up" background={true} />
          </div>
        </p>
      </div>

      <div className={styles.container}>
        <Head>
          <title>Enhanced Interiors</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <main className={styles.main}>

          <Text maxWidth="50%">
            Lorem ipsum dolor sit amet, consectetur adipiscin suscipit quis vel erat. scing elit. Nam a risus id ipsum dictum susciscing elit. Nam a risus id ipsum dictum susci
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a risus id ipsum dictum suscipit quis vel erat. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a ris vel erat. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a risus id ipsum dictum suscipit quis vel erat. scing elit. Nam a risus id ipsum dictum susci
          </Text>

          <div style={{padding: "2em 0"}}/>

          <ContentStack>
            <ImageCap path='/Intro_1.png'/>
            <ImageCap path='/Intro_2.png'/>
            <ImageCap path='/Intro_3.png'/>
            <ImageCap path='/Intro_4.png'/>
          </ContentStack>

          <div style={{padding: "2em 0"}}/>

          <Section
            title="About"
            text="Enhanced Interiors takes the guess work out of decorating your home. Using AR we size up your walls and do the calculations to make sure what you see is what you get!"
            id="about"
            src="/placeholder.png"
            orientation={true}
            button={true}
          />
          <div style={{padding: "2em 0"}}/>
          <Section 
            title="App"
            text="Hosting a wide variety of providers, we let you select from a wide catalogue of designs to help you make that crucial decision and get things looking the way you want."
            id="review"
            src="/app.jpg"
            orientation={false}
          />

          <div style={{padding: "2em 0"}}/>

          <div style={{padding: '1em 0em'}} id="freq">
            <Heading fontSize="2em">Frequently Asked Questions</Heading>
            <div style={{padding: "2em 0"}}/>
            <Text className={styles.listStylePosition}>
              <b>A:</b> How much is the app?
            </Text>
          </div>
          <div className={styles.question}>
              <Text style={{textAlign: 'center'}} >
                <b>A:</b> In pulvinar consequat lacus ut rutrum. Sed consequat facilisis fringilla. Aliquam at iaculis sem, eget fringilla diam.
              </Text>
          </div>

          <div style={{padding: ".5em 0"}}/>

          <div style={{padding: '1em 0em'}} id="freq">
            <Text className={styles.listStylePosition}>
              <b>Q:</b> Question
            </Text>
          </div>

          <div className={styles.question}>
              <Text style={{textAlign: 'center'}} >
                <b>A:</b> In pulvinar consequat lacus ut rutrum. 
              </Text>
          </div>

          <div style={{padding: ".5em 0"}}/>

          <div style={{padding: '1em 0em'}} id="freq">
            <Text className={styles.listStylePosition}>
              <b>Q:</b> Question
            </Text>
          </div>
          <div className={styles.question}>
              <Text style={{textAlign: 'center'}} >
                <b>A:</b> Sed consequat facilisis fringilla. Aliquam at iaculis sem, eget fringilla diam.              
              </Text>
          </div>

          <div style={{padding: "2em 0"}}/>

          <ContentStack>
            <ImageCap path='/nick.jpg' caption="I am an indecisive person who needs to see or visualise changes before I can commit. EI is an absolute saviour during the planning stages of my home deco. I could visualise how various patterns would look on my walls and consulate with my husband before we made our final decisions, and got a good price from comparing! Would highly recommend!" fill={true} name="Nick"/>
            <ImageCap path='/katie.png' caption="EI's measurement tool is also really handy as I have very high ceilings so this estimate and rolls suggestions are convenient. Excellent! fixes a real problem and gives you price estimated at the same time." fill={true} name="Katie"/>   
            <ImageCap path='/callum.jpg' caption="Genuinely useful use of AR technology but not just showcase or gimmicky! This app really make my home DIY project way easier! Save lots of time and money, and we picked something bolder than I’d normally have imagined." fill={true} name="Callum"/> 
          </ContentStack>

        </main>

        <footer className={styles.footer} >
          <HStack spacing='50vw'>
            <span className={styles.logoB}>
            </span>
            <div style={{position: 'relative', top: '3vh'}}>
              <h4>Contacts</h4>
              <p>Telephone: +44 8938473038</p>
              <p>55, stStreet, City</p>
              <p>NR24 8HL</p>
            </div>
          </HStack>
        </footer>

      </div>
    </div>
  )
}
